# Generated by Django 2.2.7 on 2023-02-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamarthyaApp', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
