# Generated by Django 4.0.6 on 2023-02-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamarthyaApp', '0004_alter_payment_id_alter_payments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_unpaid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
