# Generated by Django 4.0.6 on 2023-02-22 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SamarthyaApp', '0005_remove_payment_paid_unpaid_remove_payment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payments',
            new_name='bool_model',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.RenameField(
            model_name='bool_model',
            old_name='paid_unpaid',
            new_name='true_false',
        ),
    ]
